### PR TITLE
24 add desiredstate

### LINKED ISSUE #24: Add desiredState to StateMachine
The goal is to not say `proc.stop()` when you want to stop a process but to `proc.push_desired_state()`. This way there can be no error in the way the process flows through the states. Additionally the desiredState approach makes it possible to synchronously trigger asynchronous tasks like shutting down gracefully without loosing track.

Here are what to do on DesiredState and CurrentState

DS Idle
HealthCheck | Healthy => proc.stop() | set State to `Stopping` - retain DS
Stopping => { do nothing waiting for Stopped} - retain DS
_ => set State to Idle - remove DS

DS Ready
HealthCheck | Healthy => proc.stop() | set State to `Stopping` - retain DS
Stopping => { do nothing waiting for Stopped} - retain DS
_ => set State to Ready - remove DS

DS HealthCheck
Healthy => proc.stop() | set State to `Stopping` - retain DS
Stopping => { do nothing waiting for Stopped} - retain DS
_ => set State to Ready - remove DS

DS Healthy
Healthy => proc.stop() | set State to `Stopping` - retain DS
Stopping => { do nothing waiting for Stopped} - retain DS
_ => set State to Ready - remove DS

DS Stopping | Stopped
Stopping | Stopped => {} - remove DS
_ => proc.stop() | set State to `Stopping` - remove DS

DS WaitingForRetry | Failed | Finished => don't make any sense.

### PR DESCRIPTION
**Pull request by fbruggem**
Changes:

- Added `desiredStates` and implemented them in the handlers for the JSONRPC (will rework them next - implemented for - testing them now)
- Removed `process::stop()` in favor of `kill_gracefully()` and `kill_forcefully()`.
- Changed `Process` dependent code to be in the `impl` block.
- Removed the `State` trait because of unnecessary complexity. In both cases we have to route the call to the correct enum anyways, because you can'f force a trait on each variant of an enum. [ref](https://stackoverflow.com/questions/51567350/can-traits-be-used-on-enum-types)

closes #24

### CODE REVIEW

**Comment by winstonallo** [comment]
I agree we don't need the trait, but just so I understand, what do you mean by `you can't force a trait on each variant of an enum`? 

If I do something like this, `Debug` is enforced on each variant of the `Enum`
```rust
struct NoDebug {}

#[derive(Debug)]
enum Enum {
    A(i32),
    B(String),
    C(NoDebug),
}
```

```
➜  ls git:(master) ✗ cargo build
   Compiling ls v0.1.0 (/home/winstonallo/mastery/ls)
error[E0277]: `NoDebug` doesn't implement `Debug`
 --> src/main.rs:7:7
  |
3 | #[derive(Debug)]
  |          ----- in this derive macro expansion
...
7 |     C(NoDebug),
  |       ^^^^^^^ `NoDebug` cannot be formatted using `{:?}`
  |
  = help: the trait `Debug` is not implemented for `NoDebug`
  = note: add `#[derive(Debug)]` to `NoDebug` or manually `impl Debug for NoDebug`
  = note: this error originates in the derive macro `Debug` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider annotating `NoDebug` with `#[derive(Debug)]`
  |
1 + #[derive(Debug)]
2 | struct NoDebug {}
  |

For more information about this error, try `rustc --explain E0277`.
error: could not compile `ls` (bin "ls") due to 1 previous error
```

File: src/run/proc.rs [hunk 1]
```diff
@@ -63,12 +74,15 @@ extern "C" fn kill(_signum: c_int) {
...
 impl Process {
     pub fn state(&self) -> ProcessState {
-        self.state.lock().expect("something went terribly wrong").clone()
+        self.state.clone()
     }
 
-    pub fn update_state(&mut self, new_state: ProcessState) {
-        let mut handle = self.state.lock().expect("something went terribly wrong");
-        *handle = new_state;
+    // pub fn update_state(&mut self, new_state: ProcessState) {
```
Comment (winstonallo) [inline src/run/proc.rs]: is this function still needed? if not pls remove :)

**Review by winstonallo — CHANGES_REQUESTED** [review]
pls no commented out code, otherwise looks great

**Comment by fbruggem** [comment]
> If I do something like this, Debug is enforced on each variant of the Enum

Yes but with that you get code-gen (macros) made on each variant. So that you already have the added code. Like the debug -> now everything can be printed.

What you can't do is say `impl Trait for Enum` and now be *required* to make `impl Trait for Enum::Variant` on each variant. This would be the `monitor()` and `desire()` function in our case. 

TLDR: You can add stuff on each variant with macros. You can't require the developer to implement a function on each variant with a trait.

**Review by winstonallo — APPROVED** [review]
lgtm
